name: Laravel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Set up environment
        run: php -r "copy('.env.example', '.env');"
      - name: Generate key
        run: php artisan key:generate
      - name: Install dependencies
        run: |
          composer install
          npm install
      - name: Build application
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create database
        run: touch database/database.sqlite
      - name: Execute unit tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit --log-junit tests/report.xml
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: tests/report.xml

  style:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute code style tests
        run: vendor/bin/pint --test
